---

apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-cm
data:
  master.conf: |
    bind 0.0.0.0
  slave.conf: |
    slaveof redis-0.redis.default.svc.cluster.local 6379

---

apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
spec:
  ports:
  - port: 6379
  clusterIP: None
  selector:
    app: redis

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
spec:
  selector:
    matchLabels:
      app: redis 
  serviceName: redis
  replicas: 3
  template:
    metadata:
      labels:
        app: redis 
    spec:
      initContainers:
      - name: init-redis
        image: redis:3.2.10-alpine
        command:
        - sh
        - "-c"
        - |
          set -ex
          if [[ ${HOSTNAME} == 'redis-0' ]]; then
            cp /mnt/config-map/master.conf /etc/redis/redis.conf
          else
            cp /mnt/config-map/slave.conf /etc/redis/redis.conf
          fi
        volumeMounts:
        - name: redis-config
          mountPath: /mnt/config-map
        - name: redis-server-volume
          mountPath: /etc/redis
      volumes:
        - name: redis-config
          configMap:
            name: redis-cm
        - name: redis-server-volume
          emptyDir: {}
      containers:
      - name: redis
        image: redis:3.2.10-alpine
        args:
          - "/etc/redis/redis.conf"
        readinessProbe:
          exec:
            command:
            - sh
            - "-c"
            - "redis-cli -h $(hostname) ping"
        livenessProbe:
          exec:
            command:
            - sh
            - "-c"
            - "redis-cli -h $(hostname) ping"
        volumeMounts:
          - name: redis-server-volume
            mountPath: /etc/redis
